apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxrc
spec:
  replicas: 5  
  selector:
    app: app1
template:
metadata: 
  name: nginxpod
  labels:
    app: app1
spec:
  -  name: nginxpod
     image: nginx
     ports:
     - containerPort: 80