apiVersion: v1
kind: ReplicationController
metadata: 
  name: myapp
spec: 
  replicas: 1
  selector: 
    app: app2
  template:
    metadata: 
      name: myapp
      labels: 
        app: app2
    spec:
      containers:
      - name: mynginx
        image: suneel0526/k8s-docker-jenkins
        ports:
        - containerPort: 8080