apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: app1
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 30200   
  selector:
    app:  app1
  externalIPs:
    - 192.168.56.1